language: node_js

node_js:
  - "8.11.1"

cache:
  directories:
    - node_modules

before_script: 
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
after_success:
  - npm run coverage